version: '3'
services:
  website:
    image: my-nginx-container
    ports:
      - "8080:80"
    restart: always
  website2:
    image: my-nginx-container
    ports:
      - "8081:80"
    restart: always
  website3:
    image: my-nginx-container
    ports:
      - "8082:80"
    restart: always
  website4:
    image: my-nginx-container
    ports:
      - "8083:80"
    restart: always
  website5:
    image: my-nginx-container
    ports:
      - "8084:80"
    restart: always
